{
 "title": "Airflow",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Quantidade de Dags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_dagbag_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Running Dags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_executor_running_tasks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Success TI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_ti_successes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error TI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_ti_failures", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pool - Open Slots",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_pool_open_slots", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pool - Queued Slots",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_pool_queued_slots_default_pool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool - Running Slots",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_pool_running_slots_default_pool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool - Starving Slots",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_pool_starving_tasks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Scheduler - Running Slots",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler - Starving Slots",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_starving",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler - Executable",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_executable",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor - Open Slots",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_executor_open_slots", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Executor - Queued Slots",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_executor_queued_tasks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Executor - Running Slots",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_executor_running_tasks", "legendFormat": "__auto" }
   ]
  }
 ]
}