apiVersion: v1
kind: ConfigMap
metadata:
  name: recipes
data:
  postgres.yaml: |
    source:
      type: postgres
      config:
        host_port: postgresql.postgresql.svc:5432
        database: postgres

        username: postgres
        password: postgres

        profiling:
          enabled: true
          profile_table_level_only: false

    sink:
      type: "datahub-rest"
      config:
          server: "http://datahub-datahub-gms.datahub.svc:8080"
  superset.yaml: |
    source:
      type: "superset"
      config:
        username: admin
        password: admin
        connect_uri: http://superset.superset.svc:8088/

    sink:
      type: "datahub-rest"
      config:
        server: "http://datahub-datahub-gms.datahub.svc:8080"

