apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-clusters
data:
  kafka-cluster-v10-kafka-bootstrap.yaml: |
    kafka:
      clusters:
        - name: kafka-cluster-v10-kafka-bootstrap
          bootstrapServers: kafka-cluster-v10-kafka-bootstrap.strimzi.svc:9092
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false
