apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datahub-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${REPO_URL}
    targetRevision: ${REPO_BRANCH}
    path: ${REPO_PATH}
    directory:
      recursive: true
    helm:
      passCredentials: true
      chart: datahub-backend
      #parameters:
  destination:
    server: https://kubernetes.default.svc
    namespace: datahub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true