apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-admin
  labels:
    app: kafka-admin
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kafka-admin-deploy
        image: theuzz1/kafka-admin:latest
